# This file serves as a template for the configuration file. Copy it and edit the values as needed.
# Use --config parameter to specify the path to the configuration file.

[indexer]
start_index = 0
new_block_check_millis = 1000
batch_size = 10000
num_parallel_req = 10
log_range = 10

[srcdb]
host = "95.216.64.174"
port = 5432
database = "postgres"
schema = "flare"
username = "postgres"
password = "1qazxsw2#EDC123456789"

[destdb]
host = "127.0.0.1"
port = 5432
database = "postgres"
schema = "public"
username = "postgres"
password = "1qazxsw2#EDC123456789"
log_queries = false
history_drop = 86400           # 7 days
drop_table_at_start = true

[logger]
level = "INFO"
file = "./logger/logs/flare-data-db-indexer.log"
console = true

[timeout]
backoff_max_elapsed_time_seconds = 300
timeout_milis = 1000
